---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: dotenv
          secret:
            secretName: laravel-env
      containers:
        - name: php
          image: php-image
          imagePullPolicy: Always
          volumeMounts:
            - name: dotenv
              mountPath: /php-app/secrets
          env:
            - name: DOTENV_PATH
              value: /php-app/secrets
        - name: nginx
          image: nginx-image
          imagePullPolicy: Always
      initContainers:
        - name: migrate
          env:
            - name: DOTENV_PATH
              value: /php-app/secrets
          volumeMounts:
            - name: dotenv
              mountPath: /php-app/secrets
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              php artisan migrate --seed --force
