---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: sqlite
          emptyDir: { }
        - name: dotenv
          secret:
            secretName: laravel-env
      containers:
        - name: php
          image: php-image
          imagePullPolicy: Always
          volumeMounts:
            - name: sqlite
              mountPath: /php-app/sqlite
            - name: dotenv
              mountPath: /php-app/secrets
          env:
            - name: DB_CONNECTION
              value: sqlite
            - name: DB_DATABASE
              value: /php-app/sqlite/database.sqlite
            - name: DOTENV_PATH
              value: /php-app/secrets
        - name: nginx
          image: nginx-image
          imagePullPolicy: Always
      initContainers:
        - name: migrate
          env:
            - name: DB_CONNECTION
              value: sqlite
            - name: DB_DATABASE
              value: /php-app/sqlite/database.sqlite
            - name: DOTENV_PATH
              value: /php-app/secrets
          volumeMounts:
            - name: sqlite
              mountPath: /php-app/sqlite
            - name: dotenv
              mountPath: /php-app/secrets
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              touch /php-app/sqlite/database.sqlite
              php artisan migrate
