name: deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  deploy:
    env:
      platform: linux/amd64,linux/arm64
      # should use a release/version to mark tags
      DOCKER_IMAGE: shop-x-hedron

    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer,phpunit
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.platform }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and push PHP
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.platform }}
          context: .
          push: true
          file: ./docker/php/Dockerfile
          target: prod
          tags: docker.io/${{ secrets.HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:php
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push NGINX
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.platform }}
          context: .
          push: true
          file: ./docker/nginx/Dockerfile
          target: prod
          tags: docker.io/${{ secrets.HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:nginx
          cache-from: type=gha
          cache-to: type=gha,mode=max
